#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jun 12 22:04:32 2023

@author: visionlab
"""


import numpy as np
import pickle
#import pcl
dataset = "test"
import open3d as o3d

def createCloud(cloud_array, label_array):
    cloud = o3d.geometry.PointCloud()    
    cloud.points = o3d.utility.Vector3dVector(cloud_array)
    o3d.io.write_point_cloud("test.ply", cloud)
    
      

#load scannet_test.pickle file
file_pickle = open('/media/visionlab/Data/Tübitak-1001-KT/data/cls/PLY_FILES/Rose/Rose_01/Rose_01.pickle', 'rb')
xyz = pickle.load(file_pickle, encoding='latin1') # encoding keyword for python3
labels = pickle.load(file_pickle, encoding='latin1') # encoding keyword for python3
file_pickle.close()

createCloud(xyz[0], labels[0])




